"""Collect credentials from host into ~/.caw/auth/ and generate manifest + setup script."""

from __future__ import annotations

import textwrap
from pathlib import Path

from rich.console import Console

from .manifest import AgentManifest, Manifest
from .providers import PROVIDERS, AgentAuthProvider, CollectedFile

console = Console()

# Canonical auth directory
AUTH_DIR = Path.home() / ".caw" / "auth"


def _resolve_providers(agent_names: list[str]) -> list[AgentAuthProvider]:
    """Resolve provider names to provider objects."""
    if "all" in agent_names:
        return list(PROVIDERS.values())
    result = []
    for name in agent_names:
        if name not in PROVIDERS:
            available = ", ".join(PROVIDERS.keys())
            raise ValueError(f"Unknown agent '{name}'. Available: {available}")
        result.append(PROVIDERS[name])
    return result


def _validate_providers(
    providers: list[AgentAuthProvider], src_home: Path
) -> tuple[list[AgentAuthProvider], list[tuple[AgentAuthProvider, list[str]]]]:
    """Validate providers, returning (valid, skipped) lists."""
    valid = []
    skipped = []
    for provider in providers:
        missing = provider.validate(src_home)
        if missing:
            skipped.append((provider, missing))
        else:
            valid.append(provider)
    return valid, skipped


def _generate_setup_container_sh(manifest: Manifest) -> str:
    """Generate a standalone POSIX shell script for container-side setup."""
    return textwrap.dedent("""\
        #!/bin/sh
        # setup-container.sh — generated by `caw auth collect`
        # Sets up credential symlinks and config copies inside a container.
        # Usage: setup-container.sh <mount_point> <container_home> <username>
        set -e

        MOUNT_POINT="${1:-/tmp/caw_auth}"
        CONTAINER_HOME="${2:-/home/playground}"
        USERNAME="${3:-playground}"

        MANIFEST="$MOUNT_POINT/manifest.json"
        if [ ! -f "$MANIFEST" ]; then
            echo "[setup-container] ERROR: manifest.json not found at $MANIFEST"
            exit 1
        fi

        echo "[setup-container] Setting up auth files from $MOUNT_POINT..."

        # Parse manifest with jq and process each file
        jq -r '
            .agents | to_entries[] | .value.files[] |
            [.src, .container_target, .strategy, .mode] | @tsv
        ' "$MANIFEST" | while IFS=$(printf '\\t') read -r src target strategy mode; do
            target_path="$CONTAINER_HOME/$target"
            source_path="$MOUNT_POINT/$src"

            # Create parent directory
            target_dir=$(dirname "$target_path")
            mkdir -p "$target_dir"

            if [ "$strategy" = "symlink" ]; then
                # Remove existing file/symlink, create symlink to mount
                rm -f "$target_path"
                ln -s "$source_path" "$target_path"
                echo "[setup-container]   symlink: $target -> $source_path"
            elif [ "$strategy" = "copy" ]; then
                cp "$source_path" "$target_path"
                chmod "$mode" "$target_path"
                echo "[setup-container]   copy: $target (mode $mode)"
            fi

            # Fix ownership of the target file/symlink and its parent dir (non-recursive).
            # Avoid -R: target_dir can be $HOME itself, which would walk everything.
            chown "$USERNAME:$USERNAME" "$target_dir" 2>/dev/null || true
            chown -h "$USERNAME:$USERNAME" "$target_path" 2>/dev/null || true
        done

        echo "[setup-container] Auth setup complete."
    """)


def collect(
    agents: list[str] | None = None,
    source_home: str | None = None,
    force: bool = False,
    link: bool = False,
) -> Path:
    """Collect credentials from host into ~/.caw/auth/.

    Args:
        agents: List of agent names, or None / ["all"] for all agents.
        source_home: Home directory to read credentials from.
        force: Overwrite existing auth dir without prompting.
        link: Also run link() after collecting.

    Returns:
        Path to the auth directory.
    """
    src_home = Path(source_home) if source_home else Path.home()
    auth_dir = AUTH_DIR

    console.print("[bold]Collecting credentials into ~/.caw/auth/[/bold]\n")

    # Resolve providers
    selected = _resolve_providers(agents or ["all"])

    # Validate
    valid_providers, skipped_providers = _validate_providers(selected, src_home)

    if not valid_providers:
        console.print("[red]Error: No valid agent credentials found.[/red]")
        for provider, missing in skipped_providers:
            console.print(f"  [dim]{provider.name}:[/dim] missing {', '.join(missing)}")
        raise SystemExit(1)

    # Warn about missing agents
    if skipped_providers:
        for provider, missing in skipped_providers:
            console.print(f"[yellow]Warning: {provider.name} credentials not found:[/yellow] {', '.join(missing)}")
        console.print()

    # Show what we'll process
    names = [p.name for p in valid_providers]
    console.print(f"[dim]Agents:[/dim] {', '.join(names)}\n")

    # Describe each provider
    for provider in valid_providers:
        desc = provider.describe(src_home)
        console.print(f"[bold]{provider.name}:[/bold] {desc}")
    console.print()

    # Collect files from all providers
    all_files: list[CollectedFile] = []
    manifest = Manifest.create(host_home=str(src_home))

    for provider in valid_providers:
        console.print(f"[bold]Collecting {provider.name} files...[/bold]")
        collected = provider.collect(src_home)
        all_files.extend(collected)

        # Build manifest entry
        agent_manifest = AgentManifest(files=[cf.manifest_file for cf in collected])
        manifest.agents[provider.name] = agent_manifest

    # Write everything
    if auth_dir.exists():
        import shutil

        # Preserve .backups directory across re-collections
        backups = auth_dir / ".backups"
        backup_tmp = None
        if backups.exists():
            backup_tmp = auth_dir.parent / ".backups_tmp"
            if backup_tmp.exists():
                shutil.rmtree(backup_tmp)
            backups.rename(backup_tmp)

        shutil.rmtree(auth_dir)
        auth_dir.mkdir(parents=True)

        if backup_tmp and backup_tmp.exists():
            backup_tmp.rename(auth_dir / ".backups")
    else:
        auth_dir.mkdir(parents=True)

    # Write collected files
    for cf in all_files:
        out_path = auth_dir / cf.manifest_file.src
        out_path.parent.mkdir(parents=True, exist_ok=True)
        out_path.write_bytes(cf.content)
        out_path.chmod(int(cf.manifest_file.mode, 8))

    # Write manifest
    manifest.save(auth_dir / "manifest.json")

    # Write setup-container.sh
    setup_script = auth_dir / "setup-container.sh"
    setup_script.write_text(_generate_setup_container_sh(manifest))
    setup_script.chmod(0o755)

    # Set directory permissions
    for d in auth_dir.rglob("*"):
        if d.is_dir():
            d.chmod(0o755)

    console.print("\n[bold green]Done![/bold green]")
    console.print(f"Auth files written to: {auth_dir}")
    console.print("\n[dim]Contents:[/dim]")
    for cf in all_files:
        strategy = cf.manifest_file.strategy
        ftype = cf.manifest_file.type
        console.print(f"  [dim]{cf.manifest_file.src}[/dim]  ({ftype}, {strategy})")
    console.print("  [dim]manifest.json[/dim]")
    console.print("  [dim]setup-container.sh[/dim]")

    # Optionally link
    if link:
        console.print()
        from .linker import link as do_link

        do_link(agents=agents, force=force)

    return auth_dir
